
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author waniya_mustafa
 */
public class CatProductsFrame extends javax.swing.JFrame {

        customer customerInstance = null;
        ArrayList<Product> productsList;
        String type;

        /**
         * Creates new form CatProductsFrame
         */
        public CatProductsFrame(customer customerInstance, ArrayList<Product> productsList, String type) {
                this.type = type;
                this.customerInstance = customerInstance;
                this.productsList = productsList;
                initComponents();
                ImageIcon background_img = new ImageIcon(
                                "C:\\Users\\MINAHIL SHAKOOR\\Desktop\\Grocery_Management_System_Java\\SMMS_Images\\ProductsFrame.jpeg",
                                "");
                Image img = background_img.getImage();
                Image temp_img = img.getScaledInstance(807, 456, Image.SCALE_SMOOTH);
                background_img = new ImageIcon(temp_img);
                JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                backgrnd.setBounds(0, 0, 807, 456);
                this.add(backgrnd);
                getContentPane().setBackground(new java.awt.Color(204, 204, 204)); // Set content pane background
                this.setTitle("Products");
                this.setResizable(false);
                showDetailsBtn.setOpaque(true);
                this.setLocationRelativeTo(null);

                backBtn.setOpaque(true);
                setExtendedState(JFrame.MAXIMIZED_BOTH);
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                String[] col = { "ID", "Name", "Quantity", "Price" };
                DefaultTableModel tableModel = new DefaultTableModel(null, col);
                productsTable.setModel(tableModel);
                productsTable.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
                TableColumnModel colModel = productsTable.getColumnModel();
                colModel.getColumn(0).setPreferredWidth(30);
                colModel.getColumn(1).setPreferredWidth(450);
                colModel.getColumn(2).setPreferredWidth(30);
                colModel.getColumn(3).setPreferredWidth(80);
                DefaultCellEditor editor = (DefaultCellEditor) productsTable.getDefaultEditor(Object.class);
                editor.setClickCountToStart(20);
                for (int i = 0; i < productsList.size(); i++) {

                        if (productsList.get(i).getType().equals(type)) {
                                int ID = productsList.get(i).getID();
                                int qty = productsList.get(i).getQuantity();
                                double price = productsList.get(i).getPrice();
                                String data[] = { String.valueOf(ID), productsList.get(i).getName(),
                                                String.valueOf(qty),
                                                String.valueOf(price) };
                                tableModel.addRow(data);

                        }

                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPopupMenu1 = new javax.swing.JPopupMenu();
                jScrollPane1 = new javax.swing.JScrollPane();
                productsTable = new javax.swing.JTable();
                backBtn = new javax.swing.JButton();
                showDetailsBtn = new javax.swing.JButton();

                setExtendedState(JFrame.MAXIMIZED_BOTH);
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                productsTable.setBackground(new java.awt.Color(204, 204, 204));
                productsTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
                productsTable.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
                productsTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "ID", "Name", " Quantity", "Price"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(productsTable);
                if (productsTable.getColumnModel().getColumnCount() > 0) {
                        productsTable.getColumnModel().getColumn(0).setMinWidth(50);
                        productsTable.getColumnModel().getColumn(0).setMaxWidth(100);
                        productsTable.getColumnModel().getColumn(2).setMinWidth(50);
                        productsTable.getColumnModel().getColumn(2).setMaxWidth(100);
                        productsTable.getColumnModel().getColumn(3).setMinWidth(80);
                        productsTable.getColumnModel().getColumn(3).setMaxWidth(120);
                }

                backBtn.setBackground(new java.awt.Color(255, 102, 102));
                backBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
                backBtn.setText("Back");
                backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
                backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                backBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                backBtnActionPerformed(evt);
                        }
                });

                showDetailsBtn.setBackground(new java.awt.Color(255, 102, 102));
                showDetailsBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
                showDetailsBtn.setText("Show Details");
                showDetailsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
                showDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                showDetailsBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(65, 65, 65)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(backBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                138,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(showDetailsBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                177,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                680,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(62, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(72, 72, 72)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                252,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                55,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(showDetailsBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(backBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(35, 35, 35)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
        }// GEN-LAST:event_backBtnActionPerformed

        private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showDetailsBtnActionPerformed

                int row = productsTable.getSelectedRow();
                if (row == -1) {
                        JOptionPane.showMessageDialog(this, "Please Select a Product to show its Details!", "ALERT",
                                        JOptionPane.INFORMATION_MESSAGE);

                } else {
                        String val = productsTable.getModel().getValueAt(row, 0).toString();
                        int i = Integer.parseInt(val);
                        ProductFrame obj1 = new ProductFrame(productsList, i, customerInstance);
                        obj1.setVisible(true);

                }
        }// GEN-LAST:event_showDetailsBtnActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton backBtn;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable productsTable;
        private javax.swing.JButton showDetailsBtn;
        // End of variables declaration//GEN-END:variables
}
