
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author waniya_mustafa
 */
public class LoginFrame extends javax.swing.JFrame {

    customer customerInstance = null;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SMMS_Images\\LoginFrame.png",
                "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1600, 850, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1600, 850);
        this.add(backgrnd);
        this.setTitle("Login");
        this.setResizable(false);
        loginBtn.setOpaque(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setExtendedState(6);
        setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Hubballi", 1, 26)); // NOI18N
        jLabel1.setText("Enter Your User ID:");

        IDField.setBackground(new java.awt.Color(204, 204, 204));
        IDField.setText("Enter ID Here");
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 102, 102));
        loginBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(204, 204, 204));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hubballi", 1, 24)); // NOI18N
        jLabel3.setText("Enter Your Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginBtnActionPerformed
        if (IDField.getText().length() != 0 && passwordField.getText().length() != 0) {
            String line = "";
            String ID = IDField.getText();
            ID = ID.trim();
            try {
                File myObj = new File(
                        "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                                + ID + ".txt");
                Scanner myReader = new Scanner(myObj);

                while (myReader.hasNextLine()) {
                    line = myReader.nextLine();

                }
                String[] res = line.split("[,]", 0);
                customerInstance = new customer(Integer.parseInt(res[0]), res[1], res[4], res[3], res[2], res[5]);
                if (customerInstance.getPassword().equals(passwordField.getText())) {
                    JOptionPane.showMessageDialog(this, "Login Successful!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    MenuFrame obj = new MenuFrame(customerInstance);
                    obj.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Password! \n Try Again!", "ERROR",
                            JOptionPane.ERROR_MESSAGE);

                }
                myReader.close();
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Account with this ID does NOT exist! ", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
            }
            try {
                ArrayList<order> orders = new ArrayList<>();
                File myObj = new File(
                        "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                                + ID + "_orders.txt");
                Scanner myReader = new Scanner(myObj);

                while (myReader.hasNextLine()) {
                    if (line.length() > 2) {
                        line = myReader.nextLine();
                        String[] res = line.split("[,]", 0);
                        order csOrder = new order(Integer.parseInt(res[0]), res[1], Integer.parseInt(res[2]),
                                Double.valueOf(res[3]), "prev");
                        orders.add(csOrder);
                    }

                }
                customerInstance.setOrders(orders);

                myReader.close();
            } catch (FileNotFoundException e) {

            }

        } else {
            JOptionPane.showMessageDialog(this, "ID or Password can not be empty!", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }// GEN-LAST:event_loginBtnActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IDFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
