
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.ObjectName;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystexm/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author waniya_mustafa
 */
public class MenuFrame extends javax.swing.JFrame {

    ArrayList<Product> products;
    customer obj = null;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame(customer obj) {

        this.obj = obj;
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SMMS_Images\\Menu.png", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1600, 850, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1600, 850);
        this.add(backgrnd);
        this.setTitle("User Menu");
        this.setResizable(false);
        showCartBtn.setOpaque(true);
        showCatBtn.setOpaque(true);
        showDetailsBtn.setOpaque(true);
        showPrevOrdersBtn.setOpaque(true);
        logoutBtn.setOpaque(true);
        changePssBtn.setOpaque(true);
        this.setLocationRelativeTo(null);

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showCatBtn = new javax.swing.JButton();
        showDetailsBtn = new javax.swing.JButton();
        showCartBtn = new javax.swing.JButton();
        showPrevOrdersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        changePssBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        showCatBtn.setBackground(new java.awt.Color(255, 102, 102));
        showCatBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showCatBtn.setText("Categories");
        showCatBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showCatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showCatBtn);
        showCatBtn.setBounds(650, 90, 260, 80);

        showDetailsBtn.setBackground(new java.awt.Color(255, 102, 102));
        showDetailsBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showDetailsBtn.setText("View Details");
        showDetailsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showDetailsBtn);
        showDetailsBtn.setBounds(650, 310, 260, 80);

        showCartBtn.setBackground(new java.awt.Color(255, 102, 102));
        showCartBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showCartBtn.setText("Cart");
        showCartBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showCartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showCartBtn);
        showCartBtn.setBounds(650, 200, 260, 80);

        showPrevOrdersBtn.setBackground(new java.awt.Color(255, 102, 102));
        showPrevOrdersBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showPrevOrdersBtn.setText("View Orders");
        showPrevOrdersBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showPrevOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPrevOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPrevOrdersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showPrevOrdersBtn);
        showPrevOrdersBtn.setBounds(650, 430, 260, 80);

        logoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(650, 670, 260, 80);

        changePssBtn.setBackground(new java.awt.Color(255, 102, 102));
        changePssBtn.setFont(new java.awt.Font("Hoefler Text", 1, 25)); // NOI18N
        changePssBtn.setText("Change Password");
        changePssBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        changePssBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePssBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changePssBtn);
        changePssBtn.setBounds(650, 550, 260, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showDetailsBtnActionPerformed
        UserInfoFrame obj1 = new UserInfoFrame(obj);
        obj1.setVisible(true);

    }// GEN-LAST:event_showDetailsBtnActionPerformed

    private void changePssBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changePssBtnActionPerformed
        ChangePasswordFrame object = new ChangePasswordFrame(obj);
        object.setVisible(true);

    }// GEN-LAST:event_changePssBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        String info = obj.getID() + "," + obj.getName() + "," + obj.getPassword() + "," + obj.getAddress() + ","
                + obj.getPhoneNumber() + "," + obj.getGender();

        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID() + ".txt");

            myWriter.write(info);
            myWriter.close();
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID() + "_orders.txt");
            ArrayList<order> or = obj.getOrders();
            for (int i = 0; i < or.size(); i++) {
                myWriter.write(or.get(i).toString() + "\n");

            }
            myWriter.close();
            JOptionPane.showMessageDialog(this, "Logged Out Successfully!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_logoutBtnActionPerformed

    private void showCatBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCatBtnActionPerformed
        String line;

        products = new ArrayList<>();
        File myObj = new File(
                "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\productsDetails.txt");
        Scanner myReader;
        try {
            myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                line = myReader.nextLine();
                String[] result = line.split("[,]", 0);
                if (result[1].equals("EL")) {
                    Product el = new Electronics(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(el);
                } else if (result[1].equals("KA")) {
                    Product ka = new kitchen(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(ka);
                } else if (result[1].equals("Dairy")) {
                    Product dairy = new Dairy(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(dairy);
                } else if (result[1].equals("COS")) {
                    Product cos = new Cosmetics(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(cos);
                } else if (result[1].equals("FG")) {
                    Product fg = new FruitAndVegitables(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(fg);
                } else if (result[1].equals("HE")) {
                    Product he = new Households(Integer.parseInt(result[0]), Integer.parseInt(result[3]),
                            Double.parseDouble(result[4]), result[2], result[1], result[5], result[6]);
                    products.add(he);
                }

            }
            CategoriesFrame object = new CategoriesFrame(obj, products);
            object.setVisible(true);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_showCatBtnActionPerformed

    private void showPrevOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPrevOrdersBtnActionPerformed
        // TODO add your handling code here:
        if (obj.getOrders().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You have NO previous orders!", "ALERT",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            PrevOrdersFrame obj1 = new PrevOrdersFrame(obj);
            obj1.setVisible(true);

        }

    }// GEN-LAST:event_showPrevOrdersBtnActionPerformed

    private void showCartBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCartBtnActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        ArrayList<order> ors = obj.getOrders();
        for (int j = 0; j < ors.size(); j++) {
            if (ors.get(j).getType().equals("curr")) {
                flag = true;
                break;
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(this, "Your Cart is Empty!", "ALERT", JOptionPane.INFORMATION_MESSAGE);

        } else {
            CartFrame obj1 = new CartFrame(obj, products);
            obj1.setVisible(true);
        }

    }// GEN-LAST:event_showCartBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePssBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton showCartBtn;
    private javax.swing.JButton showCatBtn;
    private javax.swing.JButton showDetailsBtn;
    private javax.swing.JButton showPrevOrdersBtn;
    // End of variables declaration//GEN-END:variables
}
